### ISSUE TITLE
New install broke adapter 

### ISSUE THREAD

**Issue by Anzic23** [instalator/ioBroker.mercury#11]
после восстановления iobroker на новой системе (новый контейнер) начинается опрос, но в конце не может записать данные в объект. лог:
```

2020-06-15 22:35:41.475 - debug: mercury.0 (7555) Ответ получен, парсим:
--
2020-06-15 22:35:41.475 - debug: mercury.0 (7555) * monthEnergy - index: 0 response: {"type":"Buffer","data":[43,0,0,0,0,255,255,255,255,0,0,0,0,255,255,255,255,11,25]} length: 19
2020-06-15 22:35:41.476 - debug: mercury.0 (7555) # Все данные прочитали, сохраняем полученные данные. #
2020-06-15 22:35:41.476 - debug: mercury.0 (7555) ------------ setObjects -------------
2020-06-15 22:35:41.477 - warn: mercury.0 (7555) The id "1768243" has an invalid type!: Expected "string" or "object", received "number".
2020-06-15 22:35:41.477 - warn: mercury.0 (7555) This will be refused in future versions. Please report this to the developer.
2020-06-15 22:35:41.499 - warn: mercury.0 (7555) The id "1768243" has an invalid type!: Expected "string" or "object", received "number".
2020-06-15 22:35:41.500 - warn: mercury.0 (7555) This will be refused in future versions. Please report this to the developer.
2020-06-15 22:35:41.510 - error: mercury.0 (7555) uncaught exception: Cannot read property 'val' of null
2020-06-15 22:35:41.510 - error: mercury.0 (7555) TypeError: Cannot read property 'val' of null
at /opt/iobroker/node_modules/iobroker.mercury/main.js:611:27
at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-06-15 22:35:41.511 - debug: mercury.0 (7555) cleaned everything up...
2020-06-15 22:35:41.512 - error: mercury.0 (7555) uncaught exception: Cannot read property 'val' of null
2020-06-15 22:35:41.513 - error: mercury.0 (7555) TypeError: Cannot read property 'val' of null
at /opt/iobroker/node_modules/iobroker.mercury/main.js:611:27
at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-06-15 22:35:41.513 - error: mercury.0 (7555) uncaught exception: Cannot read property 'val' of null
2020-06-15 22:35:41.513 - error: mercury.0 (7555) TypeError: Cannot read property 'val' of null
at /opt/iobroker/node_modules/iobroker.mercury/main.js:611:27
at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-06-15 22:35:41.514 - error: mercury.0 (7555) uncaught exception: Cannot read property 'val' of null
2020-06-15 22:35:41.514 - error: mercury.0 (7555) TypeError: Cannot read property 'val' of null
at /opt/iobroker/node_modules/iobroker.mercury/main.js:611:27


```

**Comment by instalator** [comment]
### 0.1.3
